-- MySQL Script generated by MySQL Workbench
-- Sun Dec  9 20:02:55 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema testing_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `testing_db` ;

-- -----------------------------------------------------
-- Schema testing_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testing_db` DEFAULT CHARACTER SET latin1 ;
USE `testing_db` ;

-- -----------------------------------------------------
-- Table `testing_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testing_db`.`users` ;

CREATE TABLE IF NOT EXISTS `testing_db`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;